language: bash

script:
    - wget -q https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
    - sudo apt-get install -y unzip
    - sudo unzip terraform_0.11.5_linux_amd64.zip -d /tmp
    - sudo mv /tmp/terraform /usr/local/bin/
    - terraform --version
    - terraform init
    - terraform apply -var "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" -var "AWS_SECRET_KEY=$AWS_SECRET_KEY" -var-file=ami.tfvars -auto-approve
