# This is a sample build configuration for Other.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: atlassian/default-image:latest

pipelines:
  default:
    - step:
        script:
          - wget https://releases.hashicorp.com/packer/1.2.1/packer_1.2.1_linux_amd64.zip
          - wget https://releases.hashicorp.com/terraform/0.11.5/terraform_0.11.5_linux_amd64.zip
          - sudo apt-get install -y unzip
          - sudo unzip packer_1.2.1_linux_amd64.zip -d /tmp
          - sudo mv /tmp/packer /usr/local/bin/
          - sudo unzip terraform_0.11.5_linux_amd64.zip -d /tmp
          - sudo mv /tmp/terraform /usr/local/bin/
          - packer --version
          - terraform --version
          - packer validate packer/app-server.json
          - packer build -machine-readable packer/app-server.json | tee build.log
          - "AMI=$(grep 'artifact,0,id' build.log | cut -d, -f6 | cut -d: -f2)"
          - terraform init
          - terraform apply -var "ami=$AMI" -var "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" -var "AWS_SECRET_KEY=$AWS_SECRET_KEY" -auto-approve
