
Vagrant.configure('2') do |config|
  config.ssh.insert_key = false
  config.vm.box_download_insecure = true
  config.vm.box = 'beubi/xenial64'
  config.vm.network 'forwarded_port', guest: 22, host: 2020, auto_correct: true
  config.vm.network 'forwarded_port', guest: 80, host: 8800, auto_correct: true
  config.vm.provision :shell, path: '../provisioning/base.sh', privileged: false
  config.vm.provision :shell, path: '../provisioning/bootstrap.sh', privileged: false


  config.vm.provider :virtualbox do |vb, override|
    override.vm.box = 'bento/ubuntu-16.04'
    override.vm.box_version = '2.2.9'
    override.vm.network :private_network, ip: '10.11.12.9'
    vb.memory = 2536
    vb.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/qem', '1']
  end

end
